name: Run tests

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      localize-db:
        image: mysql:latest
        env:
          MYSQL_DATABASE: localize
          MYSQL_ROOT_PASSWORD: root
          MYSQL_PASSWORD: admin
          MYSQL_USER: user
        ports:
          - 3306:3306
    steps:
      - name: Run php setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - uses: actions/checkout@v3
      - name: Copy .env.test.local
        run: php -r "file_exists('.env.test.local') || copy('.env.test', '.env.test.local');"
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Install php-cs-fixer
        run: composer install --working-dir=tools/php-cs-fixer -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - run: make test-psr
      - run: make test-static
      - run: make test-unit
      - name: Execute tests with db
        run: make test-api
